version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 4000:8000
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  postgres:
    image: postgres
    volumes:
      - postgres-db:/var/lib/postgresql/data
volumes:
  postgres-db:
